### ISSUE TITLE
Bad error message : "Nullable object must have a value" when required field not populated

### ISSUE THREAD

**Issue by Terebi42** [zzzprojects/EntityFramework-Effort#109]
Given the following models (and importantly, the configuration)

```
public class EffortEntity
	{
		[Key]
		public Guid Id { get; set; }
		public Guid? ChildId { get; set; }
		public virtual EffortEntityChild Child { get; set; }

	}

	public class EffortEntityChild
	{
		[Key]
		public Guid Id { get; set; }
	}

	internal class EntityConfig : EntityTypeConfiguration<EffortEntity>
	{
		public EntityConfig()
		{
			HasRequired(a => a.Child)
				.WithMany()
				.HasForeignKey(c => c.ChildId);
		}
	}
```
The following unit test will fail

```
               var connection = Effort.DbConnectionFactory.CreateTransient();
		var context = new EffortContext(connection, true);

			var entity = new EffortEntity()
			{
				Id = Guid.NewGuid()
			};

			context.Entities.Add(entity);
			context.SaveChanges();
```

But with no indication of which column is causing the problem, or that the problem is at all a missing required field. 
```

Test method EffortNullableTest.UnitTest1.TestMethod1 threw exception: 
System.Data.Entity.Infrastructure.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.Entity.Core.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Nullable object must have a value.
    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at lambda_method(Closure )
--- End of inner exception stack trace ---
    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Effort.Internal.CommandActions.InsertCommandAction.CreateAndInsertEntity(ITable table, IList`1 memberBindings, Transaction transaction)
   at Effort.Internal.CommandActions.InsertCommandAction.ExecuteNonQuery(ActionContext context)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
--- End of inner exception stack trace ---
    at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
--- End of inner exception stack trace ---
    at System.Data.Entity.Internal.InternalContext.SaveChanges()
```

**Comment by Terebi42** [comment]
At a minimum, having the table name that fails output in the exception would be awesome, since many times you are saving a graph of objects and have no idea which entity failed. But having the column identified too would be even better.  The table name is available In the CreateAndInsertEntity call, which could catch this exception, add the table name, and rethrow. 

I'm not sure how to catch which field is the problem though.

**Comment by JonathanMagnan** [comment]
Hello @Terebi42 ,

Do you think you could provide us a test project with this issue?

It will make easier/faster for my developer to getting started for investigating it.

_We now always ask for a project since we found out that most issues are missing some essential information or are resolved by the requestor when creating it_

_(Even if the issue seem very easy to reproduce, by getting a test project, it allow us to give a faster support and better experience for the support of all our free libraries)_

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Thank a lot @Terebi42 ,

The issue has been assigned to a developer.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Terebi42 ,

The issue is caused because you mark the child `HasRequired(a => a.Child)`. So the EntityType assume the `ChildId` will have a value. So the property type become `Guid` instead of `Guid?` and then some logic later throw an error since the type doesn't match.

Specifying the child is optional make all the code work again.

```csharp
HasOptional(a => a.Child)
	.WithMany()
	.HasForeignKey(c => c.ChildId);
```

Let me know if that explains correctly the current behavior.

Best Regards,

Jonathan

**Comment by Terebi42** [comment]
@JonathanMagnan  Sorry, I think you may have misunderstood the problem. The test is supposed to fail, because a required property is not populated. But the error is not helpful, it does not tell you which table nor which column is missing. Thus when you have a large object graph that is saving back, it is very difficult to track down the problem.  (Imagine that the problem property is the great-great-great grandchild of the parent object etc)

**Comment by JonathanMagnan** [comment]
Hello @Terebi42 ,

Oh sorry, I see what you mean.

My bad, I should have re-read the request before answering it.

We will check if we can improve the error message.

Best Regards,

Jonathan

**Comment by Terebi42** [comment]
@JonathanMagnan Yeah, sorry, I could have made it clearer by putting asserts into the test testing for the table and column names to be explicit about the behavior I was looking for.
