### ISSUE TITLE
KeyNotFoundException during CreateIfNotExists() call

### ISSUE THREAD

**Issue by AGBrown** [zzzprojects/EntityFramework-Effort#113]
##### Environment:

- Visual Studio 2013 Update 5
- .Net 4.5 project

Nugets and versions <details><summary>(expand for packages.config).</summary>
<p>

```xml
  <package id="Effort.EF6" version="1.3.3" targetFramework="net45" />
  <package id="Effort.Extra.EF6" version="1.4.0" targetFramework="net45" />
  <package id="EntityFramework" version="6.2.0" targetFramework="net45" />
  <package id="NMemory" version="1.1.0" targetFramework="net45" />
  <package id="NUnit" version="3.7.1" targetFramework="net45" />
  <package id="NUnit3TestAdapter" version="3.10.0" targetFramework="net45" />
```

</p></details>

Test are run in parallel using `[assembly: Parallelizable(ParallelScope.All)]`.

##### Sample test

This exception can be reproduced with a single test, duplicated 4 times within the fixture and run in parallel on a multi-core workstation both within visual studio and using the nunit console runner.

The sample test code is:  <details><summary>(expand for full code).</summary>
<p>

```c#
[Test]
public void CanUseEffort()
{
    var fixture = new Fixture(); // autofixture
    //  --- Use Extra.Effort to pre-seed the database
    var data = new ObjectData();
    var newModel = new Apple { Id = fixture.Create<int>(), Name = fixture.Create<string>() };
    data.Table<Apples>().Add(newModel);

    var dataLoader = new ObjectDataLoader(data);
    using (var connection = DbConnectionFactory.CreateTransient(dataLoader))
    using (var context = new TestDbContext(connection, false))
    {
        //  Initialise the transient database - this fails intermittently
        context.Database.CreateIfNotExists();
        var dbSet = context.Apples;
        var actual = dbSet.ToList();
        Assert.That(actual.Count, Is.EqualTo(1));
    }
}
```

</p></details>

##### Problem details

When multiple tests are run in parallel, the call to `context.Database.CreateIfNotExists();` in the test intermittently fails with the exception:

```
Error : EffortPoc.EffortDemoFixture.CanPreLoadEntities
System.Collections.Generic.KeyNotFoundException : The key '8f8c545d-5f35-4161-a84a-39ef98c2b003' was not found in the data collection.
   at Effort.Extra.ObjectDataLoader.CreateTableDataLoaderFactory() in C:\Dev\Effort.Extra\Effort.Extra\ObjectDataLoader.cs:line 61
   at Effort.Internal.DbManagement.DbContainer.Initialize(DbSchema schema)
   at Effort.Provider.EffortProviderServices.<>c__DisplayClass4.<DbCreateDatabase>b__3(DbConnection x)
   at Effort.Provider.EffortProviderServices.Wrap[T](DbConnection connection, Func`2 action)
   at System.Data.Entity.Internal.DatabaseOperations.Create(ObjectContext objectContext)
   at System.Data.Entity.Internal.DatabaseCreator.CreateDatabase(InternalContext internalContext, Func`3 createMigrator, ObjectContext objectContext)
   at System.Data.Entity.Database.CreateIfNotExists()
   at EffortPoc.EffortDemoFixture.CanPreLoadEntities() in EffortDemoFixture.cs:line 51
```

The guid in the error changes each time the exception is encountered.

##### Other details

If the tests are run sequentially, the first test selected to be run takes a few seconds. Subsequent tests take milliseconds. If the tests are run in parallel then all of the tests that run first (at the same time) take a few seconds to run and intermittently one of them will fail with this exception. Presumably this is because all of them are doing the various bits of initialisation work on the db context, and that initialisation isn't concurrency-safe.

**Comment by AGBrown** [comment]
I updated the test - i copied the wrong MVCE into the issue. After looking at this more I've also realised that the final frame of the stack trace is an Effort.Extra.EF6 type, so maybe this can just be closed - I'll open a copy at https://github.com/christophano/Effort.Extra/issues as well
