### ISSUE TITLE
Specified cast is not valid only when using Effort In-Memory DB

### ISSUE THREAD

**Issue by nick-beers** [zzzprojects/EntityFramework-Effort#119]
I'm performing 2 left outer joins and plugging data into a DTO that has a property defined as `public long PersonId { get; set; }` and the EF data model also has a property defined as `public long PersonId { get; set; }`. When I use the query normally in the application the code works, but when I use an Effort in-memory database `DbConnectionFactory.CreateTransient()` I receive the following exception:

```
StackTrace:	
at Effort.Provider.EffortDataReader.GetInt64(Int32 ordinal)
   at lambda_method(Closure , Shaper )
   at System.Data.Entity.Core.Common.Internal.Materialization.Coordinator`1.ReadNextElement(Shaper shaper)
   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.SimpleEnumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ...
Result Message:	System.InvalidCastException : Specified cast is not valid.
```
I think there may be a bug in Effort related to reading `long` types into non-entities even thought it should be long to long.

**Comment by JonathanMagnan** [comment]
Hello @nick-beers ,

Do you think you could provide a "working" project example/test with this issue?

It will make easier/faster for my developer to getting started for investigating it.

_You can send it to info@zzzprojects.com if you need to keep the source private_

_We now always ask for a project since we found out that most issues are missing some essential information, have some syntax mistake or are resolved by the requestor when creating it_

_(Even if the issue seem very easy to reproduce, by getting a test project, it allow us to give a faster support and better experience for the support of all our free libraries)_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
