### ISSUE TITLE
 Argument types do not match

### ISSUE THREAD

**Issue by pauliusg** [zzzprojects/EntityFramework-Effort#138]
Hi, 

runing EF6 + Effor test I am getting this exception:
```csharp
Test method Tests.Test threw exception: 
System.Data.Entity.Core.EntityCommandExecutionException: An error occurred while executing the command definition. See the inner exception for details. ---> System.ArgumentException: Argument types do not match
    at System.Linq.Expressions.Expression.Condition(Expression test, Expression ifTrue, Expression ifFalse)
   at Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbCaseExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbCaseExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbExpression expression)
   at Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbComparisonExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbComparisonExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbExpression expression)
   at Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbAndExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbAndExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbExpression expression)
   at Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbFilterExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbFilterExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbExpression expression)
   at Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbProjectExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbProjectExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbExpression expression)
   at Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbIsEmptyExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbIsEmptyExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbExpression expression)
   at Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbNotExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbNotExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbExpression expression)
   at Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbCaseExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbCaseExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbExpression expression)
   at Effort.Internal.DbCommandTreeTransformation.TransformVisitor.VisitExpressions(IList`1 expressions)
   at Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbNewInstanceExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbNewInstanceExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbExpression expression)
   at Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbProjectExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbProjectExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbExpression expression)
   at Effort.Internal.CommandActions.QueryCommandAction.ExecuteDataReader(ActionContext context)
   at Effort.Provider.EffortEntityCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<Reader>b__c(DbCommand t, DbCommandInterceptionContext`1 c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
 --- End of inner exception stack trace ---
    at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.<GetElementFunction>b__3[TResult](IEnumerable`1 sequence)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Any[TSource](IQueryable`1 source, Expression`1 predicate)
   at ...
```

However with EF6 + real MS SQL database I don't get this exception.

To reproduce, you need entity with DateTime property and DateTime? property:
```csharp
public class Test
{
	public DateTime StartDate { get; set; }
	public DateTime? EndDate { get; set; }
}
```

And query:
```csharp
var anyResult = testRepository
	.AsQueryable()
	.Select(t => new { t.StartDate, EndDate = t.EndDate ?? DateTime.MaxValue })
	.Any(t => t.StartDate >= t.EndDate);
```

**Comment by pauliusg** [comment]
Found workaround:
```csharp
var anyResult = testRepository
	.AsQueryable()
	.Select(t => new { t.StartDate, EndDate = t.EndDate ?? new DateTime(9999, 12, 31) })
	.Any(t => t.StartDate >= t.EndDate);
```

But it will not work if you will write:
```csharp
var maxDate = new DateTime(9999, 12, 31);
var anyResult = testRepository
	.AsQueryable()
	.Select(t => new { t.StartDate, EndDate = t.EndDate ?? maxDate })
	.Any(t => t.StartDate >= t.EndDate);
```

**Comment by JonathanMagnan** [comment]
Hello @pauliusg ,

Thank you for reporting the issue and the workaround.

We will try to look next week if that's possible to support the one that doesn't work.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by pauliusg** [comment]
Hi @JonathanMagnan,

issue if fixed. Thanks!
