### ISSUE TITLE
Runtime exception when mapping TPH inheritance

### ISSUE THREAD

**Issue by johnknoop** [zzzprojects/EntityFramework-Effort#147]
We have an abstract base class called NotificationScheme with a few subclasses, like EmailNotificationScheme, AssigneeNotificationScheme etc. These are happed to a single table with discriminator column. We've used DevArt´s Entity Developer to generate the mapping files, and everything works like a charm when running the application.

This is how the NotificationScheme mapping looks:

```
    public partial class EmailNotificationSchemeMapping : EntityTypeConfiguration<EmailNotificationScheme> {

        public EmailNotificationSchemeMapping() {
            this
                .Map(tph => { 
                    tph.Requires("Recipient").HasValue("Email");
                    tph.ToTable("NotificationScheme");
                });
            this.Property(p => p.EmailAddress)
                    .IsRequired()
                    .IsUnicode(false);
            OnCreated();
        }

        partial void OnCreated();

    }
```

When I run this in a test using Effort as in-memory database however, the code above causes this exception:

```
Message: System.MissingMethodException : Method not found: 'System.Data.Entity.ModelConfiguration.Configuration.EntityMappingConfiguration`1<!0> System.Data.Entity.ModelConfiguration.Configuration.EntityMappingConfiguration`1.ToTable(System.String)'.

Stack trace:
at BreezeProduction.Models.Entity.Local.Mapping.EmailNotificationSchemeMapping.<>c.<.ctor>b__0_0(EntityMappingConfiguration`1 tph)
   at System.Data.Entity.ModelConfiguration.EntityTypeConfiguration`1.Map(Action`1 entityMappingConfigurationAction)
   at BreezeProduction.Models.Entity.Local.Mapping.EmailNotificationSchemeMapping..ctor() in C:\work\breeze\src\BreezeProduction\Models\Entity\Local\Mapping\EmailNotificationSchemeMap.cs:line 22
   at BreezeProduction.Models.Entity.Local.BreezeLocalDatabase.OnModelCreating(DbModelBuilder modelBuilder) in C:\work\breeze\src\BreezeProduction\Models\Entity\Local\LocalDatabase.BreezeLocalDatabase.cs:line 251
   at System.Data.Entity.Internal.LazyInternalContext.CreateModelBuilder()
   at System.Data.Entity.Internal.LazyInternalContext.CreateModel(LazyInternalContext internalContext)
   at System.Data.Entity.Internal.RetryLazy`2.GetValue(TInput input)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   at System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   at System.Data.Entity.Internal.Linq.InternalSet`1.ActOnSet(Action action, EntityState newState, Object entity, String methodName)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Add(Object entity)
   at System.Data.Entity.DbSet`1.Add(TEntity entity)
```

Looking at the stack trace, the exception doesn't occur in any of your code, but since it works when running against a real MySql database, I still thought I might report this here. Any ideas what this might be?

**Comment by JonathanMagnan** [comment]
Hello @johnknoop ,

Do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @johnknoop ,

This issue will be closed since we haven't heard back from you.

Feel free to reopen if you can provide further information.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Sure,

As soon as we get the project, we will re-open this issue to investigate it.

Best Regards,

Jonathan

**Comment by johnknoop** [comment]
Hi

Just wanted to drop a message that we were able to get it working by upgrading version. When using version 6.1.3 of EF, version 3.0.0 of NMemory and version 2.0.2 of Effort, everything works as expected.
