### ISSUE TITLE
CachedDataLoader fails with EntityDataLoader using ContextFactory

### ISSUE THREAD

**Issue by jbhelm** [zzzprojects/EntityFramework-Effort#188]
### Description
The CachedDataLoader throws an ArgumentException of "Keyword not supported: 'Argument'." when using an underlying EntityDataLoader that is initialized with the empty constructor and uses the EntityFrameworkEffortManager.ContextFactory.

### Exception
System.ArgumentException
  HResult=0x80070057
  Message=Keyword not supported: 'Argument'.
  Source=System.Data.Common
  StackTrace:
   at System.Data.Common.DbConnectionStringBuilder.get_Item(String keyword)
   at Effort.DataLoaders.CachingDataLoader.Effort.DataLoaders.IDataLoader.set_Argument(String value)
   at Effort.Provider.EffortConnection.CreateDbContainer()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Effort.Internal.Caching.ConcurrentCache`2.Get(TKey key, Func`1 factory)
   at Effort.Internal.Caching.DbContainerStore.GetDbContainer(String instanceId, Func`1 databaseFactoryMethod)
   at Effort.Provider.EffortConnection.Open()
   at Effort.Provider.EffortProviderServices.Wrap[T](DbConnection connection, Func`2 action)
   at Effort.Provider.EffortProviderServices.DbCreateDatabase(DbConnection connection, Nullable`1 commandTimeout, StoreItemCollection storeItemCollection)
   at System.Data.Entity.Core.Common.DbProviderServices.CreateDatabase(DbConnection connection, Nullable`1 commandTimeout, StoreItemCollection storeItemCollection)
   at System.Data.Entity.Core.Objects.ObjectContext.CreateDatabase()
   at System.Data.Entity.Internal.DatabaseOperations.Create(ObjectContext objectContext)
   at System.Data.Entity.Internal.DatabaseCreator.CreateDatabase(InternalContext internalContext, Func`3 createMigrator, ObjectContext objectContext)
   at System.Data.Entity.Internal.InternalContext.CreateDatabase(ObjectContext objectContext, DatabaseExistenceState existenceState)
   at System.Data.Entity.Database.Create(DatabaseExistenceState existenceState)
   at System.Data.Entity.CreateDatabaseIfNotExists`1.InitializeDatabase(TContext context)
   at System.Data.Entity.Internal.InternalContext.<>c__DisplayClass66_0`1.<CreateInitializationAction>b__0()
   at System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)
   at System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization()
   at System.Data.Entity.Internal.LazyInternalContext.<>c.<InitializeDatabase>b__58_0(InternalContext c)
   at System.Data.Entity.Internal.RetryAction`1.PerformAction(TInput input)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeDatabaseAction(Action`1 action)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeDatabase()
   at System.Data.Entity.Internal.InternalContext.Initialize()
   at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   at System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   at System.Data.Entity.Infrastructure.DbQuery`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.Single[TSource](IQueryable`1 source, Expression`1 predicate)
<snip>

### Project
```
Effort.EntityFrameworkEffortManager.ContextFactory = context => new DataContext();
var actualDataLoader = new Effort.DataLoaders.EntityDataLoader();
var cachedDataLoader = new Effort.DataLoaders.CachingDataLoader(actualDataLoader);
var conn = Effort.DbConnectionFactory.CreateTransient(cachedDataLoader);
```
The above executes successfully, but on first access to the database, the exception is thrown.

### Further technical details
- EF version: 6.3.0 (on .NET Core 3.0)
- EF Effort version: 2.2.5

**Comment by JonathanMagnan** [comment]
Hello @jbhelm ,

Thank you, we will look at it.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @jbhelm ,

Is there a reason why you use cachedDataLoader? At this moment, both loaders are not compatible together.

If the reason is to re-use the same data, you can do it by using `RestorePoint`

For example:

```csharp
var conn = Effort.DbConnectionFactory.CreateTransient();

// You could use your EntityDataLoader here
using (var context = new EntityContext(conn))
{
	context.EntitySimples.Add(new EntitySimple { ColumnInt = 1 });
	context.EntitySimples.Add(new EntitySimple { ColumnInt = 2 });
	context.EntitySimples.Add(new EntitySimple { ColumnInt = 3 });
	context.SaveChanges();
}

// Create a RestorePoint that will save all current entities in the "Database"
conn.CreateRestorePoint();


// Make any change
using (var context = new EntityContext(conn))
{
	context.EntitySimples.RemoveRange(context.EntitySimples);
	context.SaveChanges();
}

// Rollback to the restore point to make more tests
conn.RollbackToRestorePoint();
```

**Comment by JonathanMagnan** [comment]
Understood ;)

The v2.2.6 has been released.

Could you confirm that the CacheDataLoader + EntityDataLoader work correctly together?

**Comment by jbhelm** [comment]
Awesome, works perfectly -- thank you for the quick response!
