### ISSUE TITLE
Support for HierarchyId - Effor.EF6 does not support HierarchyId

### ISSUE THREAD

**Issue by devwaheed** [zzzprojects/EntityFramework-Effort#190]
### Description
Describe the issue or proposed feature.
unable to test HierarchyId.
Add support for HierarchyId.
Entity Framework 6.3.0 has builtin support for HierarchyId.

### Exception
   at Effort.Provider.EffortProviderManifest.GetStoreType(TypeUsage edmType)
   at System.Data.Entity.ModelConfiguration.Edm.Services.StructuralTypeMappingGenerator.MapTableColumn(EdmProperty property, String columnName, Boolean isInstancePropertyOnDerivedType)
   at System.Data.Entity.ModelConfiguration.Edm.Services.PropertyMappingGenerator.Generate(EntityType entityType, IEnumerable`1 properties, EntitySetMapping entitySetMapping, MappingFragment entityTypeMappingFragment, IList`1 propertyPath, Boolean createNewColumn)
   at System.Data.Entity.ModelConfiguration.Edm.Services.TableMappingGenerator.Generate(EntityType entityType, DbDatabaseMapping databaseMapping)
   at System.Data.Entity.ModelConfiguration.Edm.Services.DatabaseMappingGenerator.GenerateEntityTypes(DbDatabaseMapping databaseMapping)
   at System.Data.Entity.ModelConfiguration.Edm.Services.DatabaseMappingGenerator.Generate(EdmModel conceptualModel)
   at System.Data.Entity.DbModelBuilder.Build(DbProviderManifest providerManifest, DbProviderInfo providerInfo)
   at System.Data.Entity.DbModelBuilder.Build(DbConnection providerConnection)
   at System.Data.Entity.Internal.LazyInternalContext.CreateModel(LazyInternalContext internalContext)
   at System.Data.Entity.Internal.RetryLazy`2.GetValue(TInput input)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   at System.Data.Entity.Internal.InternalContext.Initialize()
   at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   at System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   at System.Data.Entity.Internal.Linq.InternalSet`1.ActOnSet(Action action, EntityState newState, Object entity, String methodName)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Add(Object entity)
   at System.Data.Entity.DbSet`1.Add(TEntity entity)
   at HierarchyExp.Program.Main(String[] args) in E:\playground\HierarchyExp\Program.cs:line 18
```
Exception message:
Unable to find store type for edmType hierarchyid, Effort does not support this data type.
```

### Project
Provide a project/solution that we can run to reproduce the issue.
here is the repo of project. its a console application.

https://github.com/devwaheed/ef6-hierarchyid-effort-issue

### Further technical details
- EF version: 6.30.
- EF Effort version: 2.6.6
- Database Provider: SQL Server

**Comment by JonathanMagnan** [comment]
Hello @devwaheed ,

Thank you for reporting,

We will look at it and add it to the default manifest.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by devwaheed** [comment]
Hi Jon,




That would be great.




Get Outlook for Android







On Mon, Nov 4, 2019 at 7:07 PM +0500, "Jonathan Magnan" <notifications@github.com> wrote:












Hello @devwaheed ,



Thank you for reporting,



We will look at it and add it to the default manifest.



Best Regards,



Jonathan





Performance Libraries


context.BulkInsert(list, options => options.BatchSize = 1000);  


Entity Framework Extensions • Entity Framework Classic • Bulk Operations •  Dapper Plus



Runtime Evaluation


Eval.Execute("x + y", new {x = 1, y = 2}); // return 3


C# Eval Function • SQL Eval Function

**Comment by JonathanMagnan** [comment]
Hello @devwaheed ,

We investigated this issue and unfortunately, that's currently a way to much complex on our side.

Unless I'm wrong, we do not either support other spatial types such as `Geography` and `Geometry`.

So unless someone provides us a pull request, I don't think it will happen soon.

However, is ignoring this property could work for you?

**Comment by devwaheed** [comment]
yeah, for now ignoring the property.

thanks for update

**Comment by JonathanMagnan** [comment]
Awesome @devwaheed, 

A quick reminder that this issue will be closed. 

But feel free to reopen it for questions, issues or feedback

best regards,

Jon
