### ISSUE TITLE
Nested transactions rollback should allow commit on parent transaction.

### ISSUE THREAD

**Issue by malylemire1** [zzzprojects/EntityFramework-Effort#208]
Nested transactions rollback should allow commit on parent transaction.
EF6 does not fail in this situation.

```
using (var transaction = Context.BeginTransaction())
{
    using (var childTransaction = Context.BeginTransaction())
    {
        childTransaction.Rollback();
    }

    transaction.Commit();
}
```

```
Exception message: typeof(System.Data.Entity.Core.EntityException): The underlying provider failed on Commit.
    ---- System.Data.Entity.Core.EntityException : The underlying provider failed on Commit.
    -------- System.Transactions.TransactionAbortedException : The transaction has aborted.
Stack trace:
 at System.Transactions.TransactionStateAborted.BeginCommit(InternalTransaction tx, Boolean asyncCommit, AsyncCallback asyncCallback, Object asyncState)
   at System.Transactions.CommittableTransaction.Commit()
   at Effort.Provider.EffortTransaction.Commit()
   at System.Data.Entity.Infrastructure.Interception.DbTransactionDispatcher.<>c.<Commit>b__6_0(DbTransaction t, DbTransactionInterceptionContext c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbTransactionDispatcher.Commit(DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.EntityClient.EntityTransaction.Commit()
```

**Comment by JonathanMagnan** [comment]
Hello @malylemire1 ,

We will look at it but I don't think anything will be done if it starts to be too complex.

I will let you know soon about it.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @malylemire1 ,

Unfortunately, my developer looked at it. The major problem is way too much custom code needs to be modified in `NMemory` (used by EF Effore). Handling correctly multiple transactions is sure possible but will make the code way too much complicated and would take way too long to code for what it worth (several days/weeks).

So due to this, we prefer not to do this request
