### ISSUE TITLE
System.InvalidOperationException: Sequence contains more than one matching element

### ISSUE THREAD

**Issue by izmailoff** [zzzprojects/EntityFramework-Effort#33]
Hi,

I'm getting this exception when I use `IQueryable`:

```
System.Data.DataException: An exception occurred while initializing the database. See the InnerException for details. ---> 
System.Data.Entity.Infrastructure.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> 
System.Data.Entity.Core.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---> 
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> 
NMemory.Exceptions.NMemoryException: Error code: GenericError ---> 
System.InvalidOperationException: Sequence contains more than one matching element

    at System.Linq.Enumerable.SingleOrDefault(IEnumerable`1 source, Func`2 predicate)
   at NMemory.Tables.TableCollection.FindTable(Type entityType)
   at NMemory.Utilities.TableCollectionExtensions.FindTable(TableCollection tableCollection)
   at NMemory.Execution.CommandExecutor.ExecuteInsert(T entity, IExecutionContext context)
   at NMemory.Tables.DefaultTable`2.InsertCore(TEntity entity, Transaction transaction)
   at Effort.Internal.DbManagement.Engine.ExtendedTable`2.InsertCore(TEntity entity, Transaction transaction)
   at NMemory.Tables.Table`2.Insert(TEntity entity, Transaction transaction)
 --- End of inner exception stack trace ---
    at NMemory.Tables.Table`2.Insert(TEntity entity, Transaction transaction)
   at Effort.Internal.Common.DatabaseReflectionHelper.WrapperMethods.InsertEntity(ITable`1 table, TEntity entity, Transaction transaction)
 --- End of inner exception stack trace ---
    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Effort.Internal.Common.DatabaseReflectionHelper.InsertEntity(ITable table, Object entity, Transaction transaction)
   at Effort.Internal.CommandActions.InsertCommandAction.CreateAndInsertEntity(ITable table, IList`1 memberBindings, Transaction transaction)
   at Effort.Internal.CommandActions.InsertCommandAction.ExecuteNonQuery(ActionContext context)
   at Effort.Provider.EffortEntityCommand.ExecuteNonQuery()
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<NonQuery>b__0(DbCommand t, DbCommandInterceptionContext`1 c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch(TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Internal.InterceptableDbCommand.ExecuteNonQuery()
   at System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
 --- End of inner exception stack trace ---
    at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
   at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update(T noChangesResult, Func`2 updateFunction)
   at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update()
   at System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__35()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction(Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   at System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass2a.<SaveChangesInternal>b__27()
   at System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute(Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
 --- End of inner exception stack trace ---
    at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   at System.Data.Entity.DbContext.SaveChanges()
   at System.Data.Entity.Migrations.History.HistoryRepository.BootstrapUsingEFProviderDdl(VersionedModel versionedModel)
   at System.Data.Entity.Internal.InternalContext.<SaveMetadataToDatabase>b__7()
   at System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)
   at System.Data.Entity.Internal.InternalContext.SaveMetadataToDatabase()
   at System.Data.Entity.Internal.DatabaseCreator.CreateDatabase(InternalContext internalContext, Func`3 createMigrator, ObjectContext objectContext)
   at System.Data.Entity.Internal.InternalContext.CreateDatabase(ObjectContext objectContext, DatabaseExistenceState existenceState)
   at System.Data.Entity.Database.Create(DatabaseExistenceState existenceState)
   at System.Data.Entity.CreateDatabaseIfNotExists`1.InitializeDatabase(TContext context)
   at System.Data.Entity.Internal.InternalContext.<>c__DisplayClassf`1.<CreateInitializationAction>b__e()
   at System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)
 --- End of inner exception stack trace ---
    at System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)
   at System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization()
   at System.Data.Entity.Internal.LazyInternalContext.<InitializeDatabase>b__4(InternalContext c)
   at System.Data.Entity.Internal.RetryAction`1.PerformAction(TInput input)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeDatabaseAction(Action`1 action)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeDatabase()
   at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   at System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   at System.Data.Entity.Infrastructure.DbQuery`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.Count(IQueryable`1 source)

   at Model.MyProj... my test method call stack here
```

to reproduce:

```
var query = db.MyEntities.Count(); // will throw the exception above FOR SOME DBCONTEXTS ONLY!!!
```

Otherwise all other tests work just fine with Effort. Created a more detailed question here:
http://stackoverflow.com/questions/36053318/effort-throws-invalidoperationexception-sequence-contains-more-than-one-matchin

I checked the DbContext that causes the problem and could not find anything special about it. Any ideas?

Thanks

**Comment by tamasflamich** [comment]
Hi @izmailoff - This seems to be an issue related to table naming. Could you tell me more info about your table mapping?

**Comment by izmailoff** [comment]
Hi @tamasflamich , unfortunately I no longer work with that project and don't have access to the code. Thanks though.

**Comment by ProoM** [comment]
+1

**Comment by JasonMisavage** [comment]
I get a similar exception. 
[stack.txt](https://github.com/tamasflamich/effort/files/483410/stack.txt)
I think it's because I have two EF contexts that both have the same table mapping `public virtual DbSet<Models.Course> Courses { get; set; }` and I am trying to use them both on the same Effort db connection.

**Comment by tamasflamich** [comment]
@JasonMisavage Makes sense. I guess this is probably an NMemory issue, since it should not allow to create two tables with the same entity type in the first place. It's quite interesting that it ends up being the same entity type though. 

Going to take a look if I get some free time.

**Comment by JasonMisavage** [comment]
This is a guess, but the RegisterTable method in https://github.com/tamasflamich/nmemory/blob/master/Main/Source/NMemory/Tables/TableCollection.cs is not checking whether the table is already in the tables collection before adding it to that collection. Could that be the problem?

**Comment by juliencousineau** [comment]
I have the same problem

**Comment by damien-raemy** [comment]
I had the same problem, but I could correct it by downloading the NMemory source code (https://github.com/tamasflamich/nmemory) and changing the TableCollection.RegisterTable method:
```
private void RegisterTable(ITable table)
{
    if (entityTypes.Contains(table.EntityType))
    {
        return;
    }

    foreach (ITableCatalog catalog in 
        this.database.DatabaseEngine.Components.OfType<ITableCatalog>())
    {
        catalog.RegisterTable(table);
    }

    this.tables.Add(table);
    this.entityTypes.Add(table.EntityType);

    this.relationMapping.Add(table, new RelationGroup());
}
```

After recompilation, this seems to work works

**Comment by JonathanMagnan** [comment]
Hello all,

The code from @damien-r has been merged a few weeks ago.

If someone still has the problem with the latest version, just let me know.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
